services:
  - type: web
    name: farm-survey-app
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farm-survey-db
          property: connectionString

databases:
  - name: farm-survey-db
    plan: free
